# Use CAF MSM8960 hardware repos
TARGET_QCOM_DISPLAY_VARIANT := caf-msm8960
TARGET_QCOM_AUDIO_VARIANT := caf-msm8960
TARGET_QCOM_MEDIA_VARIANT := caf-msm8960

# Lights
TARGET_PROVIDES_LIBLIGHT := true
